### ISSUE TITLE
Expand notification template to allow container names

### ISSUE THREAD

**Issue by MartenBE** [crazy-max/diun#479]
When I receive a notification, I get the list of images which can be updated. However, I have a lot of docker-compose.yml files running, so it gets confusing which I need to update.

e.g. Now I receive something like:

```
[diun 4.19.0] Docker tag docker.io/library/mariadb:latest has been released
[diun 4.19.0] Docker tag docker.io/library/mariadb:latest has been released
[diun 4.19.0] Docker tag docker.io/library/mariadb:latest has been released
```

But it would help if I could also include the container names in the output:

```
[diun 4.19.0] Docker tag docker.io/library/mariadb:latest has been released for nextcloud_database_1
[diun 4.19.0] Docker tag docker.io/library/mariadb:latest has been released for fireflyiii_database_1
[diun 4.19.0] Docker tag docker.io/library/mariadb:latest has been released for photoview_db_1
```

**Comment by crazy-max** [comment]
@MartenBE Which version of Diun do you use?

**Comment by MartenBE** [comment]
I use 4.19.0

**Comment by afarazit** [comment]
Hi @crazy-max, any updates for this enhancement?

**Comment by barisahmet** [comment]
Watchtower takes container name as argument to upgrade. It would be handy if we could send container name in notification to create a link, so watchtower updates the container with a single click.

**Comment by mol-lux** [comment]
I'm calling dibs on this one. I really need this :grin:  - (which of my dozen stacks is this MySQL update about, again? :mag:

**Comment by mol-lux** [comment]
Okay.... need to padel back, unfortunately.

`diun` currently works like this: (simplified):
1. It contacts the local Docker daemon to fetch a list of all (running/stopped/exited) containers 
2. For each container, it tries, by various methods, to find out what image this container was built from
3. If it is an image which has come from a registry, it will write the image information into a database. Note that the information from which container this image was read is *not* saved.

Because of point no. 3, it is unfortunately more complicated to implement this (useful) feature, than to simply add a template tag. Because, simply put, `diun` doesn't have any clue which container it has got the image information from.

I unfortunately, currently don't have time to change that implementation. So, if anyone else wants to, go ahead!

**Comment by crazy-max** [comment]
#749 should solve this issue, let me know what you think.
