### ISSUE TITLE
Tag sorting option

### ISSUE THREAD

**Issue by GeoCookie** [crazy-max/diun#518]
Hi there,

Do you know if Github Container Registry sends out tags sorted in chronological order? Or is it like Docker Hub which sends lexically sorted tags, as discussed here : https://github.com/crazy-max/diun/issues/43

I tried reading the API documentation, but I'm not sure I understand what is written 😄

Cheers

**Comment by crazy-max** [comment]
@GeoCookie I'm not sure, I need to take a look at it. Maybe we could add a [registry option](https://crazymax.dev/diun/config/regopts/) to customize tags sorting.

**Comment by ntompson** [comment]
Yes please. I have just been setting up DIUN for my containers and have found tag sorting to be an issue. It appears to be alphabetical rather than chronological or numerical.

To take a nice example, I've configured DIUN as a file provider with the following yaml excerpt:

```yaml
- name: crazymax/diun
  watch_repo: true
  max_tags: 2
  include_tags:
    - ^[\d\.]+$
```

This only returns tags that have fully formed version numbers, avoiding `latest`, betas and the like. But after starting fresh (following a `diun image remove`, the two tags that are chosen for manifest download are:

```log
diun    | Sun, 16 Jan 2022 14:04:38 AEDT INF New image found image=docker.io/crazymax/diun:4.9.0 provider=file
diun    | Sun, 16 Jan 2022 14:04:47 AEDT INF New image found image=docker.io/crazymax/diun:4.8.1 provider=file
```

As we know, the latest DIUN image tag is `4.20.1`, which is numerically higher but alphabetically lower. This is also reflected in the DIUN image list, which I assume means that DIUN would not be able to detect, say, `4.21.0` as a new version.

```
# diun image list
+---------------------------------+-----------------+----------------+----------------------+-------------------------------------------------------------------------+
| NAME                            | MANIFESTS COUNT | LATEST TAG     | LATEST CREATED       | LATEST DIGEST                                                           |
+---------------------------------+-----------------+----------------+----------------------+-------------------------------------------------------------------------+
| docker.io/crazymax/diun         |               2 | 4.9.0          | 2020-11-16T21:49:33Z | sha256:fc3a8904e77e887ccd0061b7c0700806ff32af0f56b5b9545aead75177c79bf8 |
...
+---------------------------------+-----------------+----------------+----------------------+-------------------------------------------------------------------------+
| TOTAL                           |              11 |                |                      |                                                                         |
+---------------------------------+-----------------+----------------+----------------------+-------------------------------------------------------------------------+
```

Because I currently have DIUN tracking 11 different images, I need to keep the `max_tags` low to avoid blowing up docker's limits. If it was possible to configure the tag sorting strategy, it should be possible to use a good `include_tags` filter combined with a good sorting strategy to pick the two most likely manifests to download and track.

**Comment by ntompson** [comment]
I should add: maybe I'm doing it wrong. But I can't figure out a better way to configure DIUN to track image tags by explicit version number. I don't like using the `latest` tag in my `docker-compose.yml` files as it means I don't know what I'm getting and I can't easily roll back if something breaks. Much better to be working with explicit versioning. But please let me know if there is a better way!

**Comment by ntompson** [comment]
Looking further into this and reading #43, it would appear the root cause is that docker hub returns tag lists sorted alphabetically. That would be fine if people used version tags that worked with alphabetical sorting (so `4.09`, `4.10`, ... rather than `4.9`, `4.10`, ...) but most don't, DIUN included.

I know very little about the Go language, but noticed this:

https://pkg.go.dev/github.com/hashicorp/go-version#section-readme

Perhaps this version sorting module could be used to sort the full list of tags returned by the docker hub API. It won't always get it right, but I'd wager it will most of the time.

**Comment by crazy-max** [comment]
@ntompson Thanks for your feedback. I think we could add a `sort_tags` opt that defaults if empty to the expected result from the registry and we could add options like `reverse`, `numerical`, `semver`? WDYT?

**Comment by ntompson** [comment]
Hey @crazy-max - that sounds ideal. My only comment would be that I'd suggest the `sort_tags` option should be associated with specific `provider`s, not `regopts` (ie a whole registry). So to take my example from a `file` `provider`:

```yaml
- name: crazymax/diun
  watch_repo: true
  max_tags: 2
  include_tags:
    - ^[\d\.]+$
  sort_tags: semver
```

Reason being that there is a huge diversity from one image to the next in terms of how people version their images. Generally, `semver` is going to be the right answer in the majority of cases, but I can image the odd exception. Here are a few samples of cases I've seen:

`crazymax/diun`:
4.18.0
4.19.0
4.2.0
4.20
4.20.0
4.20.1
4.3.0
4.3.1

`linuxserver/wireguard`:
v1.0.20200827-ls42
v1.0.20200827-ls43
v1.0.20200827-ls5
v1.0.20200827-ls6
v1.0.20200827-ls7
v1.0.20200827-ls8
v1.0.20200827-ls9
v1.0.20210223-ls16
v1.0.20210223-ls17
v1.0.20210223-ls18
v1.0.20210223-ls19

`linuxserver/nextcloud`:
php8-22.2.2-ls40
php8-22.2.3-ls41
php8-22.2.3-ls42
php8-22.2.3-ls43
php8-23.0.0-ls44
php8-23.0.0-ls45

`linuxserver/swag`:
version-1.20.0
version-1.21.0
version-1.22.0
version-1.8.0
version-1.9.0

`gitlab/gitlab-ce`:
9.3.1-ce.0
9.3.10-ce.0
9.3.11-ce.0
9.3.2-ce.0
9.3.3-ce.0
9.3.4-ce.0

**Comment by iay** [comment]
I got bitten by this same thing on one of the same cases (`docker.io/gitlab/gitlab-ce`, in which the tags at the end of the list are all from releases made in 2017...). So, something to address this would be welcome.

In the meanwhile, is there an easy way we can use to predict which tags are going to be used by `diun` for a given configuration without actually running it? I ended up with a configuration that works for me (even given that they frequently issue patch releases for the previous minor and even major release) but there was a fair bit of trial and error and a _lot_ of spurious notifications:

```
- name: gitlab/gitlab-ce
  watch_repo: true
  max_tags: 20
  include_tags:
    - ^(14|15)\.[\d\.]+-ce\.\d+$
```

**Comment by ntompson** [comment]
Hey @iay. As I was playing around, I found the docker v1 API a useful tool in predicting the order in which tags would be obtained by DIUN. I used a two step process to avoid hitting the API more than necessary.

Step 1: get the tags

```
% curl https://registry.hub.docker.com/v1/repositories/gitlab/gitlab-ce/tags > tags.txt
```

Step 2: hack away at a useful regex

```
% cat tags.txt | jq -r '.[] | .name' | grep -P '^(14|15)\.[\d\.]+-ce\.\d+$'
```

You may need to `sudo apt install jq` first.

**Comment by iay** [comment]
@ntompson Neat. Thanks!

**Comment by stacab** [comment]
Hi,
what's status here? Is it on the roadmap?

**Comment by crazy-max** [comment]
Started smth in https://github.com/crazy-max/diun/pull/645
