### ISSUE TITLE
[Feature Request] Manually adding an image to the images list

### ISSUE THREAD

**Issue by josejsarmento** [crazy-max/diun#681]
As per the title, I would like to manually add an image to be tracked without needing to have containers that have been spun with it. 

This would be useful for me as I have images built locally using repos found on docker.io. I would like to get notified when these are updated, so that I can then build my own version from them.

**Comment by josejsarmento** [comment]
The error when Diun encounters a local build is the following:

```
Sat, 03 Sep 2022 14:57:18 WEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: pinging container registry localhost: Get \"https://localhost/v2/\": dial tcp 127.0.0.1:443: connect: connection refused" image=localhost/local-build-image:latest provider=docker
```

I know I should probably fix this first, but I don't know how, so it would just be easier for me to add an image manually. I also believe there could be other use cases for this.

**Comment by crazy-max** [comment]
> I have images built locally using repos found on docker.io

Not sure I understand. `localhost/local-build-image:latest` cannot be tracked because it's not a registry endpoint but a local tag. If you want to track the base image used by this image, you can either use the [file provider](https://crazymax.dev/diun/providers/file/) or the [dockerfile provider](https://crazymax.dev/diun/providers/dockerfile/). See also https://crazymax.dev/diun/user-guides/docker-file-providers/
